import type { Ressource, Seance } from "./types";

// Les ressources sont réelles et libres d'accès : c'est le fonds que
// l'association recommande. Les supports « maison » de la maquette ont été
// retirés le 14 septembre 2026 ; ils reviendront quand il en existera de vrais.

export const RESSOURCES: Ressource[] = [
  {
    id: "r-01",
    titre: "Neural Networks: Zero to Hero",
    gain: "Un réseau écrit à la main, ligne par ligne, sans bibliothèque.",
    format: "video",
    niveau: "depart",
    minutes: 620,
    source: "Andrej Karpathy",
    lien: "https://karpathy.ai/zero-to-hero.html",
  },
  {
    id: "r-02",
    titre: "Dive into Deep Learning",
    gain: "Le manuel complet, avec le code exécutable à côté du texte.",
    format: "cours",
    niveau: "milieu",
    minutes: 2400,
    source: "d2l.ai",
    lien: "https://d2l.ai",
  },
  {
    id: "r-03",
    titre: "The Illustrated Transformer",
    gain: "L'attention comprise en images avant d'être lue en équations.",
    format: "notes",
    niveau: "milieu",
    minutes: 45,
    source: "Jay Alammar",
    lien: "https://jalammar.github.io/illustrated-transformer/",
  },
  {
    id: "r-04",
    titre: "Attention Is All You Need",
    gain: "Le papier d'origine. Court, dense, encore la meilleure source.",
    format: "papier",
    niveau: "fond",
    minutes: 90,
    source: "arXiv 1706.03762",
    lien: "https://arxiv.org/abs/1706.03762",
  },
  {
    id: "r-06",
    titre: "NLP Course",
    gain: "De la tokenisation au réglage fin, avec des carnets qui tournent.",
    format: "cours",
    niveau: "milieu",
    minutes: 900,
    source: "Hugging Face",
    lien: "https://huggingface.co/learn/nlp-course",
  },
  {
    id: "r-08",
    titre: "llama.cpp",
    gain: "Faire tourner un modèle sur un portable, sans carte graphique.",
    format: "atelier",
    niveau: "milieu",
    minutes: 60,
    source: "ggerganov",
    lien: "https://github.com/ggerganov/llama.cpp",
  },
  {
    id: "r-09",
    titre: "CS231n — Convolutional Neural Networks",
    gain: "Les fondations de la vision, notes de cours comprises.",
    format: "cours",
    niveau: "milieu",
    minutes: 1800,
    source: "Stanford",
    lien: "https://cs231n.github.io",
  },
  {
    id: "r-11",
    titre: "Spinning Up in Deep RL",
    gain: "L'apprentissage par renforcement, avec du code lisible.",
    format: "cours",
    niveau: "fond",
    minutes: 1200,
    source: "OpenAI",
    lien: "https://spinningup.openai.com",
  },
  {
    id: "r-12",
    titre: "Model Context Protocol",
    gain: "Brancher un modèle sur de vrais outils, sans coller des chaînes.",
    format: "cours",
    niveau: "fond",
    minutes: 180,
    source: "modelcontextprotocol.io",
    lien: "https://modelcontextprotocol.io",
  },
  {
    id: "r-14",
    titre: "The Deep Learning Book",
    gain: "La référence théorique, gratuite, à lire par morceaux.",
    format: "cours",
    niveau: "fond",
    minutes: 3000,
    source: "Goodfellow, Bengio, Courville",
    lien: "https://www.deeplearningbook.org",
  },
  {
    id: "r-15",
    titre: "PyTorch — tutoriels officiels",
    gain: "La bibliothèque par la pratique, du tenseur à l'entraînement.",
    format: "cours",
    niveau: "depart",
    minutes: 300,
    source: "PyTorch",
    lien: "https://pytorch.org/tutorials",
  },
  {
    id: "r-16",
    titre: "scikit-learn — guide de l'utilisateur",
    gain: "Tout ce qui n'est pas un réseau, et qui suffit souvent.",
    format: "cours",
    niveau: "depart",
    minutes: 480,
    source: "scikit-learn",
    lien: "https://scikit-learn.org/stable/user_guide.html",
  },
  {
    id: "r-18",
    titre: "Distill",
    gain: "L'archive des explications visuelles. Fermée, toujours juste.",
    format: "notes",
    niveau: "fond",
    minutes: 240,
    source: "distill.pub",
    lien: "https://distill.pub",
  },
];

// Aucune séance n'est datée. La liste reste vide plutôt que d'annoncer une
// date qui n'existe pas ; l'écran le dit.
export const SEANCES: Seance[] = [];
