import type { Projet } from "@/serveur/domaine/club";

// Dix-sept projets de démonstration. Tous inventés, tous portés par des
// personnes fictives. Les titres sont de longueurs inégales, les descriptions
// ne font pas le même nombre de lignes, les dates ne se suivent pas : c'est
// exprès, une liste régulière ne se juge pas.

export const PROJETS: Projet[] = [
  {
    id: "pr-01",
    slug: "sillage",
    nom: "Sillage",
    resume: "Perte de liaison vidéo d'un drone, détectée avant la coupure.",
    presentation:
      "Le flux d'un drone se dégrade toujours un peu avant de tomber. Sillage apprend cette signature sur les trames reçues et prévient deux secondes plus tôt.",
    etat: "chantier",
    categorie: "open",
    pole: "Embedded",
    porteurId: "p-camille",
    places: [
      {
        role: "Vision embarquée",
        competences: ["C++", "TensorRT", "Jetson"],
        tache: "Portage du modèle sur la carte, sous 40 ms par trame.",
      },
      {
        role: "Bancs d'essai",
        competences: ["Python", "protocoles radio"],
        tache: "Reproduction des coupures en conditions contrôlées.",
      },
    ],
    depot: "n7-ia/sillage",
    outils: ["PyTorch", "C++", "TensorRT", "ROS 2"],
    jalons: [
      { date: "2026-05-18", titre: "Premier jeu de trames capté", fait: true },
      { date: "2026-06-30", titre: "Détection hors ligne à 82 %", fait: true },
      { date: "2026-09-20", titre: "Temps réel sur la carte", fait: false },
      { date: "2026-11-15", titre: "Vol d'essai complet", fait: false },
    ],
    debut: "2026-05-04",
    maj: "2026-08-13",
  },
  {
    id: "pr-02",
    slug: "moodle-qui-repond",
    nom: "Le Moodle qui répond",
    resume: "Recherche en langage courant dans les supports de cours.",
    presentation:
      "Les supports existent, personne ne les retrouve. On indexe les PDF déposés par les enseignants et on répond avec le passage exact et sa page.",
    etat: "essai",
    categorie: "open",
    pole: "Agentic",
    porteurId: "p-ilyas",
    places: [
      {
        role: "Découpage des documents",
        competences: ["Python", "PDF", "OCR"],
        tache: "Extraction propre des schémas et des formules.",
      },
      {
        role: "Évaluation",
        competences: ["méthode", "annotation"],
        tache: "Jeu de 300 questions étiquetées, pour mesurer plutôt que croire.",
      },
      {
        role: "Interface",
        competences: ["TypeScript", "React"],
        tache: "Champ de recherche, réponse, source, deux touches.",
      },
    ],
    depot: "n7-ia/moodle-qui-repond",
    outils: ["Python", "FastAPI", "pgvector", "React"],
    jalons: [
      { date: "2026-04-22", titre: "Premier index sur un cours", fait: true },
      { date: "2026-06-08", titre: "Réponses sourcées", fait: true },
      { date: "2026-07-28", titre: "Ouverture à cinq testeurs", fait: true },
      { date: "2026-10-01", titre: "Passage en boîte à outils", fait: false },
    ],
    debut: "2026-04-15",
    maj: "2026-08-14",
  },
  {
    id: "pr-03",
    slug: "cycle",
    nom: "Cycle",
    resume: "Vieillissement de cellules lithium lu sur les courbes de charge.",
    presentation:
      "Une cellule dit son âge dans la forme de sa charge, bien avant de perdre en capacité. On cherche jusqu'où un petit modèle peut lire ça.",
    etat: "chantier",
    categorie: "open",
    pole: "ModIA",
    porteurId: "p-nino",
    places: [],
    depot: "n7-ia/cycle",
    outils: ["Python", "scikit-learn", "PyTorch"],
    jalons: [
      { date: "2026-05-26", titre: "Jeu public repris et nettoyé", fait: true },
      { date: "2026-08-05", titre: "Erreur sous 8 % sur le jeu d'essai", fait: true },
      { date: "2026-10-12", titre: "Essai sur cellules mesurées ici", fait: false },
    ],
    debut: "2026-05-19",
    maj: "2026-08-06",
  },
  {
    id: "pr-04",
    slug: "voix-haute",
    nom: "Voix haute",
    resume: "Transcription des amphis, découpée en chapitres avec les formules.",
    presentation:
      "Deux heures d'amphi deviennent un texte découpé, horodaté, cherchable. Les formules au tableau restent le point dur.",
    etat: "essai",
    categorie: "open",
    pole: "Agentic",
    porteurId: "p-sarah",
    places: [
      {
        role: "Reconnaissance de formules",
        competences: ["vision", "LaTeX"],
        tache: "Photo de tableau vers LaTeX, avec un taux d'erreur mesuré.",
      },
      {
        role: "Accessibilité",
        competences: ["ergonomie", "lecteurs d'écran"],
        tache: "Relecture du rendu avec des étudiants concernés.",
      },
    ],
    depot: "n7-ia/voix-haute",
    outils: ["Whisper", "Python", "ffmpeg"],
    jalons: [
      { date: "2026-05-11", titre: "Transcription brute d'un amphi", fait: true },
      { date: "2026-07-02", titre: "Découpage automatique en chapitres", fait: true },
      { date: "2026-09-14", titre: "Formules lisibles", fait: false },
    ],
    debut: "2026-05-05",
    maj: "2026-07-31",
  },
  {
    id: "pr-05",
    slug: "ourse",
    nom: "Ourse",
    resume: "Réponse aux appels d'offres pour des entreprises de moins de dix personnes.",
    presentation:
      "Un appel d'offres public, c'est quarante pages de formulaire pour trois pages utiles. Ourse remplit ce qui se répète et signale ce qui manque.",
    etat: "chantier",
    categorie: "business",
    pole: "ModIA",
    porteurId: "p-marion",
    places: [
      {
        role: "Terrain",
        competences: ["entretiens", "rédaction"],
        tache: "Dix entretiens avec des artisans, avant d'écrire une ligne de plus.",
      },
      {
        role: "Extraction structurée",
        competences: ["Python", "traitement du langage"],
        tache: "Des documents officiels vers un formulaire rempli.",
      },
    ],
    modele: "Abonnement par entreprise, essai gratuit sur un dossier.",
    outils: ["Python", "TypeScript", "Postgres"],
    jalons: [
      { date: "2026-06-02", titre: "Corpus de 60 appels d'offres", fait: true },
      { date: "2026-07-20", titre: "Premier dossier rempli aux trois quarts", fait: true },
      { date: "2026-09-30", titre: "Trois entreprises en essai", fait: false },
    ],
    debut: "2026-05-28",
    maj: "2026-08-11",
  },
  {
    id: "pr-06",
    slug: "quarante-huit",
    nom: "Quarante-huit",
    resume: "Inscriptions, équipes et classement du hackathon du club.",
    presentation:
      "Le tableau de bord d'un hackathon de deux jours : qui est dans quelle équipe, quel sujet, quel rendu, quel jury.",
    etat: "service",
    categorie: "open",
    pole: "Hackathon",
    porteurId: "p-fatou",
    places: [],
    depot: "n7-ia/quarante-huit",
    outils: ["Next.js", "TypeScript", "SQLite"],
    jalons: [
      { date: "2026-06-14", titre: "Inscriptions ouvertes", fait: true },
      { date: "2026-06-27", titre: "Première édition passée dessus", fait: true },
      { date: "2026-07-09", titre: "Classement en direct", fait: true },
    ],
    debut: "2026-06-01",
    maj: "2026-07-12",
  },
  {
    id: "pr-07",
    slug: "sobre",
    nom: "Sobre",
    resume: "Électricité consommée par un entraînement, mesurée carte par carte.",
    presentation:
      "On répète qu'entraîner coûte cher en énergie sans jamais donner de chiffre. Sobre branche un wattmètre et rend un graphe par expérience.",
    etat: "essai",
    categorie: "open",
    pole: "ModIA",
    porteurId: "p-quentin",
    places: [
      {
        role: "Mesure",
        competences: ["électronique", "Python"],
        tache: "Étalonnage du wattmètre contre une charge connue.",
      },
    ],
    depot: "n7-ia/sobre",
    outils: ["Python", "Grafana", "Arduino"],
    jalons: [
      { date: "2026-06-19", titre: "Banc de mesure monté", fait: true },
      { date: "2026-07-25", titre: "Trente entraînements mesurés", fait: true },
      { date: "2026-09-28", titre: "Greffon pour les carnets du club", fait: false },
    ],
    debut: "2026-06-10",
    maj: "2026-08-09",
  },
  {
    id: "pr-08",
    slug: "annales",
    nom: "Base ouverte des annales et corrigés N7",
    resume: "Recherche sur les sujets d'examen, par notion plutôt que par année.",
    presentation:
      "Les annales circulent en PDF dans des groupes privés. L'idée : un fonds commun, indexé par notion, avec les corrigés quand ils existent.",
    etat: "idee",
    categorie: "open",
    pole: "ModIA",
    porteurId: "p-basile",
    places: [
      {
        role: "Cadre juridique",
        competences: ["droit d'auteur", "rédaction"],
        tache: "Ce qu'on a le droit de rediffuser, écrit noir sur blanc.",
      },
      {
        role: "Indexation",
        competences: ["Python", "recherche"],
        tache: "Étiquetage par notion, semi-automatique.",
      },
      {
        role: "Interface",
        competences: ["React"],
        tache: "Une recherche, des filtres, rien d'autre.",
      },
    ],
    depot: "n7-ia/annales",
    outils: ["à décider"],
    jalons: [{ date: "2026-08-12", titre: "Idée déposée, personne dessus", fait: true }],
    debut: "2026-08-12",
    maj: "2026-08-12",
  },
  {
    id: "pr-09",
    slug: "micro-serre",
    nom: "Micro-serre",
    resume: "Régulation d'une serre de balcon par capteurs et modèle de croissance.",
    presentation:
      "Quatre capteurs, une pompe, un modèle qui décide quand arroser. Arrêté en juillet, le banc existe et attend quelqu'un.",
    etat: "chantier",
    enPause: true,
    categorie: "open",
    pole: "Embedded",
    porteurId: "p-lea",
    places: [],
    depot: "n7-ia/micro-serre",
    outils: ["ESP32", "MicroPython", "MQTT"],
    jalons: [
      { date: "2026-05-02", titre: "Capteurs posés", fait: true },
      { date: "2026-06-21", titre: "Arrosage automatique", fait: true },
      { date: "2026-07-06", titre: "Mis en pause", fait: true },
    ],
    debut: "2026-04-28",
    maj: "2026-07-06",
  },
  {
    id: "pr-10",
    slug: "teinte",
    nom: "Teinte",
    resume: "Gammes de couleurs accessibles, vérifiées avant la maquette.",
    presentation:
      "Un contraste se vérifie à la fin, quand il est trop tard. Teinte propose des gammes déjà conformes et refuse les paires qui ne passent pas.",
    etat: "service",
    categorie: "business",
    pole: "ModIA",
    porteurId: "p-ines",
    places: [],
    modele: "Douze euros par mois et par équipe, sans version gratuite.",
    outils: ["TypeScript", "WebGL"],
    jalons: [
      { date: "2026-05-15", titre: "Moteur de contraste", fait: true },
      { date: "2026-06-25", titre: "Greffon pour Figma", fait: true },
      { date: "2026-08-01", titre: "Deux clients d'essai", fait: true },
    ],
    debut: "2026-05-08",
    maj: "2026-08-04",
  },
  {
    id: "pr-11",
    slug: "tremplin",
    nom: "Tremplin",
    resume: "Entretien technique simulé, avec relecture du code écrit pendant.",
    presentation:
      "Un entretien d'embauche se rate faute d'entraînement. Tremplin pose des questions, laisse coder, puis rend une relecture précise plutôt qu'une note.",
    etat: "chantier",
    categorie: "open",
    pole: "Agentic",
    porteurId: "p-rim",
    places: [
      {
        role: "Banque de sujets",
        competences: ["algorithmique"],
        tache: "Quarante sujets calibrés, du plus simple au plus retors.",
      },
      {
        role: "Relecture automatique",
        competences: ["Python", "analyse statique"],
        tache: "Ce qui est faux, ce qui est lent, ce qui est illisible.",
      },
    ],
    depot: "n7-ia/tremplin",
    outils: ["Python", "TypeScript", "conteneurs"],
    jalons: [
      { date: "2026-06-30", titre: "Premier entretien joué de bout en bout", fait: true },
      { date: "2026-09-08", titre: "Vingt sujets prêts", fait: false },
    ],
    debut: "2026-06-16",
    maj: "2026-08-08",
  },
  {
    id: "pr-12",
    slug: "relecture",
    nom: "Relecture",
    resume: "Structure et style d'un rapport de projet, repris avant le rendu.",
    presentation:
      "Un rapport se juge d'abord sur sa charpente. Relecture signale les parties absentes, les figures sans légende et les phrases de trente mots.",
    etat: "essai",
    categorie: "open",
    pole: "Agentic",
    porteurId: "p-hugo",
    places: [],
    depot: "n7-ia/relecture",
    outils: ["Python", "LaTeX", "spaCy"],
    jalons: [
      { date: "2026-06-05", titre: "Détection des sections manquantes", fait: true },
      { date: "2026-07-18", titre: "Essai sur douze rapports", fait: true },
      { date: "2026-10-05", titre: "Greffon pour Overleaf", fait: false },
    ],
    debut: "2026-05-30",
    maj: "2026-08-02",
  },
  {
    id: "pr-13",
    slug: "klaxon",
    nom: "Klaxon",
    resume: "Sons de rue reconnus sur microcontrôleur, sans réseau ni serveur.",
    presentation:
      "Un modèle de 60 kilo-octets sur une carte à trois euros, qui distingue une sirène d'un klaxon. Le sujet est entier, tout est à faire.",
    etat: "idee",
    categorie: "open",
    pole: "Embedded",
    porteurId: "p-malo",
    places: [
      {
        role: "Collecte",
        competences: ["terrain", "audio"],
        tache: "Enregistrer, étiqueter, publier un jeu honnête.",
      },
      {
        role: "Compression de modèle",
        competences: ["quantification", "élagage"],
        tache: "Tenir dans 64 ko sans tomber sous 90 % de justesse.",
      },
      {
        role: "Carte",
        competences: ["C", "STM32"],
        tache: "Chaîne audio complète en temps réel.",
      },
      {
        role: "Mesure",
        competences: ["électronique"],
        tache: "Consommation réelle, en milliampères, pas en promesses.",
      },
    ],
    depot: "n7-ia/klaxon",
    outils: ["C", "STM32", "TFLite Micro"],
    jalons: [{ date: "2026-08-09", titre: "Sujet ouvert", fait: true }],
    debut: "2026-08-09",
    maj: "2026-08-09",
  },
  {
    id: "pr-14",
    slug: "affluence",
    nom: "Affluence",
    resume: "Attente au restaurant universitaire, prévue par quart d'heure.",
    presentation:
      "Les passages en caisse suffisent à prévoir la file du lendemain. Le modèle tourne, la question qui reste est celle de l'affichage.",
    etat: "essai",
    categorie: "open",
    pole: "ModIA",
    porteurId: "p-antoine",
    places: [],
    depot: "n7-ia/affluence",
    outils: ["Python", "Prophet", "Streamlit"],
    jalons: [
      { date: "2026-05-20", titre: "Historique repris", fait: true },
      { date: "2026-06-29", titre: "Erreur moyenne de 4 minutes", fait: true },
      { date: "2026-09-07", titre: "Affichage public à la rentrée", fait: false },
    ],
    debut: "2026-05-12",
    maj: "2026-07-22",
  },
  {
    id: "pr-15",
    slug: "deperdition",
    nom: "Déperdition",
    resume: "Pertes de chaleur d'un bâtiment repérées sur images thermiques.",
    presentation:
      "Une caméra thermique, un drone, et le repérage des ponts thermiques d'une façade. En pause : le matériel n'est plus disponible.",
    etat: "chantier",
    enPause: true,
    categorie: "business",
    pole: "ModIA",
    porteurId: "p-theo",
    places: [],
    modele: "Prestation au bâtiment, pour des bailleurs sociaux.",
    outils: ["Python", "OpenCV", "PyTorch"],
    jalons: [
      { date: "2026-05-07", titre: "Vingt façades photographiées", fait: true },
      { date: "2026-06-11", titre: "Segmentation des ponts thermiques", fait: true },
      { date: "2026-06-24", titre: "Mis en pause", fait: true },
    ],
    debut: "2026-04-30",
    maj: "2026-06-24",
  },
  {
    id: "pr-16",
    slug: "atlas",
    nom: "Atlas",
    resume: "Carte des projets IA menés à l'école, année après année.",
    presentation:
      "Chaque promotion refait ce que la précédente a fait. Atlas garde la trace : sujet, année, dépôt, ce qui a marché.",
    etat: "idee",
    categorie: "open",
    pole: "Agentic",
    porteurId: "p-thibaut",
    places: [
      {
        role: "Archives",
        competences: ["enquête", "patience"],
        tache: "Retrouver les projets des trois dernières promotions.",
      },
      {
        role: "Visualisation",
        competences: ["D3", "TypeScript"],
        tache: "Une carte lisible, pas un nuage de points.",
      },
    ],
    depot: "n7-ia/atlas",
    outils: ["TypeScript", "D3"],
    jalons: [{ date: "2026-07-30", titre: "Idée déposée", fait: true }],
    debut: "2026-07-30",
    maj: "2026-08-01",
  },
  {
    id: "pr-17",
    slug: "gribouille",
    nom: "Gribouille",
    resume: "Schémas électroniques dessinés à la main, relus par la machine.",
    presentation:
      "Photo d'un schéma au crayon, sortie en netlist. Ça marche sur les schémas propres ; c'est sur les ratures que tout se joue.",
    etat: "service",
    categorie: "open",
    pole: "Embedded",
    porteurId: "p-awa",
    places: [
      {
        role: "Jeu de test difficile",
        competences: ["électronique", "annotation"],
        tache: "Cent schémas mal dessinés, exprès.",
      },
    ],
    depot: "n7-ia/gribouille",
    outils: ["Python", "OpenCV", "PyTorch"],
    jalons: [
      { date: "2026-04-24", titre: "Détection des composants", fait: true },
      { date: "2026-06-06", titre: "Netlist correcte sur schéma propre", fait: true },
      { date: "2026-07-27", titre: "Version en ligne pour le club", fait: true },
    ],
    debut: "2026-04-18",
    maj: "2026-08-10",
  },
];
