import type { Numero } from "@/serveur/domaine/club";

// Numéros de démonstration. Le format est celui visé : des entrées courtes,
// une valeur brute, et une ligne qui dit pourquoi c'est là. Les mesures citées
// sont celles des projets de démonstration de cette maquette.

export const NUMEROS: Numero[] = [
  {
    id: "n-05",
    numero: 5,
    date: "2026-08-12",
    uneId: "e-501",
    entrees: [
      {
        id: "e-501",
        type: "chiffre",
        titre: "Quantification en 4 bits",
        valeur: "−1,8 point de justesse, −62 % de mémoire",
        pourquoi: "Mesuré sur nos deux modèles d'atelier. L'échange reste bon.",
        source: "Atelier quantification",
      },
      {
        id: "e-502",
        type: "outil",
        titre: "llama.cpp",
        valeur: "Un modèle utile sur un portable sans carte graphique",
        pourquoi: "C'est ce qui met l'inférence locale à portée d'un budget étudiant.",
        source: "ggerganov",
        lien: "https://github.com/ggerganov/llama.cpp",
      },
      {
        id: "e-503",
        type: "papier",
        titre: "Distillation de modèles",
        valeur: "Un petit modèle qui apprend d'un grand",
        pourquoi: "La méthode derrière la plupart des modèles qui tiennent sur une carte.",
        source: "Lecture commune du 6 août",
      },
      {
        id: "e-504",
        type: "usage",
        titre: "Évaluation avant développement",
        valeur: "30 exemples étiquetés, écrits d'abord",
        pourquoi: "Deux projets du club ont changé d'avis en écrivant leur jeu de test.",
        source: "Retour d'atelier",
      },
      {
        id: "e-505",
        type: "modele",
        titre: "Modèles à poids ouverts",
        valeur: "3 essayés chez nous, 1 tient dans 16 Go",
        pourquoi: "La contrainte n'est pas la qualité, c'est la mémoire de la carte.",
        source: "Retour d'atelier",
      },
      {
        id: "e-506",
        type: "outil",
        titre: "Model Context Protocol",
        valeur: "Un format commun pour brancher des outils",
        pourquoi: "Tremplin s'en sert : moins de colle à écrire, plus d'outils réutilisés.",
        source: "modelcontextprotocol.io",
        lien: "https://modelcontextprotocol.io",
      },
      {
        id: "e-507",
        type: "chiffre",
        titre: "Coût électrique d'un entraînement",
        valeur: "0,42 kWh pour un réglage fin de deux heures",
        pourquoi: "Le chiffre manquait pour parler d'empreinte sans agiter les mains.",
        source: "Projet Sobre",
      },
    ],
  },
  {
    id: "n-04",
    numero: 4,
    date: "2026-07-29",
    uneId: "e-401",
    entrees: [
      {
        id: "e-401",
        type: "usage",
        titre: "Recherche augmentée : ce qui rate",
        valeur: "Le découpage, pas le modèle",
        pourquoi: "Sur nos supports de cours, 70 % des mauvaises réponses viennent du découpage.",
        source: "Le Moodle qui répond",
      },
      {
        id: "e-402",
        type: "papier",
        titre: "Attention Is All You Need",
        valeur: "Huit pages qui tiennent encore",
        pourquoi: "Relu en séance. À lire une fois en entier, avant tous les résumés.",
        source: "arXiv 1706.03762",
        lien: "https://arxiv.org/abs/1706.03762",
      },
      {
        id: "e-403",
        type: "outil",
        titre: "Carnets exécutables",
        valeur: "d2l.ai : le manuel et le code côte à côte",
        pourquoi: "Le meilleur point de départ pour quelqu'un qui n'a jamais entraîné.",
        source: "d2l.ai",
        lien: "https://d2l.ai",
      },
      {
        id: "e-404",
        type: "chiffre",
        titre: "Latence sur carte embarquée",
        valeur: "38 ms par trame, cible tenue",
        pourquoi: "En dessous de 40 ms, la détection passe en temps réel sur le drone.",
        source: "Projet Sillage",
      },
      {
        id: "e-405",
        type: "modele",
        titre: "Reconnaissance vocale hors ligne",
        valeur: "Deux heures d'amphi en douze minutes de calcul",
        pourquoi: "Assez rapide pour traiter la journée le soir même.",
        source: "Projet Voix haute",
      },
    ],
  },
  {
    id: "n-03",
    numero: 3,
    date: "2026-07-15",
    uneId: "e-301",
    entrees: [
      {
        id: "e-301",
        type: "modele",
        titre: "Petits modèles de vision",
        valeur: "60 ko sur microcontrôleur, 91 % de justesse",
        pourquoi: "L'ordre de grandeur à connaître avant de dire qu'un projet est impossible.",
        source: "Revue Embedded",
      },
      {
        id: "e-302",
        type: "outil",
        titre: "Greffon de mesure d'énergie",
        valeur: "Un wattmètre et vingt lignes de Python",
        pourquoi: "Rend mesurable ce dont tout le monde parle sans chiffres.",
        source: "Projet Sobre",
      },
      {
        id: "e-303",
        type: "usage",
        titre: "Cartes modèles",
        valeur: "Une page : données, limites, usages exclus",
        pourquoi: "Devient obligatoire sur les projets Open du club.",
        source: "Décision d'atelier",
      },
      {
        id: "e-304",
        type: "papier",
        titre: "Lois d'échelle",
        valeur: "Plus grand n'est pas toujours la bonne dépense",
        pourquoi: "Utile pour arbitrer entre taille de modèle et taille de jeu de données.",
        source: "Lecture commune du 10 juillet",
      },
      {
        id: "e-305",
        type: "chiffre",
        titre: "Temps d'annotation",
        valeur: "4 h pour 300 questions étiquetées",
        pourquoi: "Le vrai coût d'une évaluation sérieuse, à prévoir dans le planning.",
        source: "Le Moodle qui répond",
      },
      {
        id: "e-306",
        type: "outil",
        titre: "Environnements jetables",
        valeur: "Un conteneur par séance, effacé après",
        pourquoi: "Plus personne ne casse son installation la veille d'un rendu.",
        source: "Retour d'atelier",
      },
    ],
  },
  {
    id: "n-02",
    numero: 2,
    date: "2026-07-01",
    uneId: "e-201",
    entrees: [
      {
        id: "e-201",
        type: "usage",
        titre: "Assistants de code en projet long",
        valeur: "Utiles sur le connu, coûteux sur le neuf",
        pourquoi: "Constat après six semaines sur trois projets du club.",
        source: "Retour d'expérience",
      },
      {
        id: "e-202",
        type: "papier",
        titre: "Explications visuelles",
        valeur: "L'archive Distill, fermée mais entière",
        pourquoi: "Reste la meilleure porte d'entrée visuelle sur les mécanismes.",
        source: "distill.pub",
        lien: "https://distill.pub",
      },
      {
        id: "e-203",
        type: "chiffre",
        titre: "Justesse sur schémas propres",
        valeur: "96 %, et 41 % sur schémas raturés",
        pourquoi: "L'écart dit où est le vrai problème, et donc le vrai sujet.",
        source: "Projet Gribouille",
      },
      {
        id: "e-204",
        type: "modele",
        titre: "Réglage fin à faible rang",
        valeur: "1 % des paramètres touchés, résultat proche",
        pourquoi: "Rend le réglage fin possible sur les cartes dont on dispose.",
        source: "Revue ModIA",
      },
    ],
  },
  {
    id: "n-01",
    numero: 1,
    date: "2026-06-17",
    uneId: "e-101",
    entrees: [
      {
        id: "e-101",
        type: "usage",
        titre: "Premier numéro",
        valeur: "Format arrêté : entrée, valeur, pourquoi",
        pourquoi: "Trois lignes par sujet. Ce qui ne tient pas en trois lignes attend.",
        source: "Le club",
      },
      {
        id: "e-102",
        type: "outil",
        titre: "Cours de traitement du langage",
        valeur: "Gratuit, avec carnets qui tournent",
        pourquoi: "Le parcours le plus court entre zéro et un modèle réglé.",
        source: "Hugging Face",
        lien: "https://huggingface.co/learn/nlp-course",
      },
      {
        id: "e-103",
        type: "papier",
        titre: "Trois passes de lecture",
        valeur: "Titre, figures, méthode, dans cet ordre",
        pourquoi: "La méthode qu'on applique aux lectures communes du club.",
        source: "Notes du club",
      },
    ],
  },
];
