import type { Numero } from "../types";
export const NUMERO_05: Numero = {
  id: "n-05",
  numero: 5,
  date: "2026-10-08",
  uneId: "e-0501",
  entrees: [
    {
      id: "e-0501",
      type: "modele",
      titre: "GPT-6 et Intelligent UI",
      valeur: "GPT-6 Sol en offres payantes, GPT-6 Luna en offres Free et Go",
      pourquoi: "Une réponse peut mêler texte, graphiques, formulaires et outils, et démarrer avant la fin du raisonnement.",
      source: "openai.com",
      lien: "https://openai.com/index/gpt-6-for-everyone",
    },
    {
      id: "e-0502",
      type: "modele",
      titre: "Claude Haiku 5.5",
      valeur: "Coût moyen annoncé environ 75 % plus bas que Haiku 4.5",
      pourquoi: "Pensé pour résumer, classer, piloter un navigateur et servir de sous-agent, à gros volume et faible latence.",
      source: "anthropic.com · via Hacker News et TLDR",
      lien: "https://www.anthropic.com/claude-haiku-5-5",
    },
    {
      id: "e-0503",
      type: "outil",
      titre: "Docker Agent",
      valeur: "Des agents décrits en YAML, lancés avec docker agent run, Apache 2.0",
      pourquoi: "Un agent, ses outils MCP et son modèle tiennent dans un fichier versionnable, puis se publient dans un registre OCI.",
      source: "github.com/docker · via TLDR",
      lien: "https://github.com/docker/docker-agent",
    },
    {
      id: "e-0504",
      type: "usage",
      titre: "Metrics Board de Pinterest",
      valeur: "Une plateforme centrale qui porte plus de 98 % des métriques d'expérimentation",
      pourquoi: "Récit de projet : création, contrôle et documentation automatisés, pour que des agents répondent sur des chiffres fiables.",
      source: "medium.com · via TLDR",
      lien: "https://medium.com/pinterest-engineering/metrics-board-building-an-agent-ready-metrics-layer-2c8fefe68756",
    },
    {
      id: "e-0505",
      type: "outil",
      titre: "Polars 2.0",
      valeur: "SQL de premier rang, type Map, débordement sur disque activé par défaut",
      pourquoi: "Tris et fenêtres débordent sur disque par défaut, pas encore les jointures. L'avance sur DuckDB sort de benchmarks menés par Polars.",
      source: "pola.rs · via TLDR",
      lien: "https://pola.rs/posts/release-polars-2/",
    },
  ],
};
