import type { Numero } from "../types";
export const NUMERO_04: Numero = {
  id: "n-04",
  numero: 4,
  date: "2026-10-07",
  uneId: "e-0401",
  entrees: [
    {
      id: "e-0401",
      type: "modele",
      titre: "Mistral Large 4",
      valeur: "1 000 milliards de paramètres, 49 milliards actifs, en aperçu public",
      pourquoi: "Entraîné en Europe, plus de 160 langues. L'API s'essaie dès maintenant, les poids ouverts sont annoncés pour fin octobre.",
      source: "mistral.ai",
      lien: "https://mistral.ai/news/mistral-large-4/",
    },
    {
      id: "e-0402",
      type: "papier",
      titre: "Les maths d'un modèle OpenAI, preuves à l'appui",
      valeur: "Des résultats publiés avec leurs preuves, en partie formalisées en Lean",
      pourquoi: "Une preuve en Lean se vérifie par ordinateur. On y lit aussi ce que coûte un résultat : calcul estimé, problèmes tentés.",
      source: "openai.com",
      lien: "https://openai.com/index/sharing-ai-progress-in-mathematics",
    },
    {
      id: "e-0403",
      type: "outil",
      titre: "AICR 1.0, les recettes NVIDIA pour clusters GPU",
      valeur: "Des configurations Kubernetes figées et validées, preuves signées à l'appui",
      pourquoi: "Ouvert, plus de 100 contributeurs. Si un cluster GPU vous attend en stage, c'est la carte des versions qui marchent ensemble.",
      source: "developer.nvidia.com",
      lien: "https://developer.nvidia.com/blog/aicr-v1-0-open-stable-and-verifiable-gpu-cluster-configuration/",
    },
    {
      id: "e-0404",
      type: "modele",
      titre: "EmbeddingGemma 2",
      valeur: "740 millions de paramètres, un seul espace pour texte, code, image, audio, vidéo",
      pourquoi: "Licence Apache 2.0, tourne sur un téléphone. De quoi faire un moteur de recherche multimodal local pour un projet étudiant.",
      source: "deepmind.google",
      lien: "https://deepmind.google/blog/embeddinggemma-2-an-open-lightweight-multimodal-embedding-model/",
    },
    {
      id: "e-0405",
      type: "usage",
      titre: "Spotify, la qualité du code à l'ère de l'IA",
      valeur: "Plus du double de changements fusionnés en un an",
      pourquoi: "Pas de lien net entre code écrit par l'IA et incidents, mais la vérification n'a pas suivi : revue, tests et retour arrière renforcés.",
      source: "engineering.atspotify.com · via TLDR",
      lien: "https://engineering.atspotify.com/2026/9/ai-changed-how-spotify-builds-what-we-learned-and-fixed-about-quality-at-higher-velocity",
    },
  ],
};
