import type { Chapitre, Lecon } from "@/serveur/domaine/academy";

// ─────────────────────────────────────────────────────────────────────────────
// Les sommaires des cours écrits.
//
// LA CORRESPONDANCE AVEC LA CHARTE, une fois pour toutes :
//
//     une LEÇON de la charte   →   un CHAPITRE de l'Academy
//     une SECTION de la leçon  →   une LEÇON de l'Academy
//
// C'est le seul découpage qui garde les deux vocabulaires lisibles côte à côte.
// Une « leçon » de la charte fait deux à trois heures et se lit en plusieurs
// fois ; en faire une seule page serait un mur. Une section, elle, se lit d'une
// traite, et c'est l'unité que l'étudiant coche.
//
// Une leçon « annoncée » figure au sommaire, grisée, non ouvrable. Elle ne
// compte pas dans l'avancement : un cours dont la moitié reste à écrire ne
// doit pas afficher 50 % à qui l'a fini.
//
// AUCUNE DURÉE N'EST ÉCRITE ICI, et c'est la raison d'être du type ci-dessous.
// Elles étaient saisies à la main, donc justes le jour où on les écrivait : le
// chapitre 1 annonçait encore 2 h 51 quand sa réécriture l'avait ramené aux
// trois quarts d'heure. Le dépôt les calcule maintenant depuis les blocs de
// chaque page (`domaine/duree.ts`), et le compilateur refuse qu'on en réécrive
// une à la main.
//
// LE SOUS-TITRE D'UNE LEÇON — son champ `resume` — s'adresse à quelqu'un qui
// n'a pas encore ouvert la page. Il dit ce qu'on va comprendre, en une ligne et
// en français courant ; il ne dit pas ce que la page démontre, et il ne nomme
// rien qu'elle n'emploie pas.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Une leçon telle qu'on l'ÉCRIT : la leçon du domaine, moins sa durée. Le
 * `Omit` n'est pas une commodité de typage, c'est l'interdit lui-même — une
 * durée réapparue dans ce fichier ne compile pas.
 */
export type LeconEcrite = Omit<Lecon, "minutes">;

export const CHAPITRES: Chapitre[] = [
  {
    id: "ch-ml-1",
    slug: "panorama-du-machine-learning",
    titre: "Panorama du machine learning",
    resume: "De quoi le domaine est fait : les mots, les objets, et un problème qu'on suit d'un bout à l'autre.",
    coursId: "c-intro-ml",
    rang: 1,
  },
  {
    id: "ch-ml-2",
    slug: "quest-ce-quun-reseau-de-neurones",
    titre: "Qu'est-ce qu'un réseau de neurones",
    resume: "Construire une machine qui lit un chiffre écrit à la main, pièce par pièce, et mesurer ce qu'elle vaut.",
    coursId: "c-intro-ml",
    rang: 2,
  },
  {
    id: "ch-ml-3",
    slug: "la-descente-de-gradient",
    titre: "La descente de gradient, comment un réseau apprend",
    resume: "Comment une machine choisit elle-même ses réglages, sans que personne n'en fixe un seul.",
    coursId: "c-intro-ml",
    rang: 3,
  },
  {
    id: "ch-ml-4",
    slug: "ce-que-fait-la-retropropagation",
    titre: "Ce que fait la rétropropagation",
    resume: "Suivre une image, et voir comment l'erreur de sortie se répercute sur chaque réglage.",
    coursId: "c-intro-ml",
    rang: 4,
  },
  {
    id: "ch-ml-5",
    slug: "le-calcul-de-la-retropropagation",
    titre: "Le calcul de la rétropropagation",
    resume: "Le même calcul pour un réseau d'autant de couches qu'on veut, et ce qu'il coûte.",
    coursId: "c-intro-ml",
    rang: 5,
  },
  {
    id: "ch-ml-6",
    slug: "loptimisation-de-lentrainement",
    titre: "L'optimisation de l'entraînement",
    resume: "Les réglages de l'entraînement, et ce qui décide qu'il aboutisse ou non.",
    coursId: "c-optim",
    rang: 1,
  },
];

export const LECONS: LeconEcrite[] = [
  // ── Chapitre 1 · Panorama du machine learning ─────────────────────────────
  //
  // Dix sections, précédées du cadre. Le chapitre a été resserré le
  // 8 septembre 2026 : ses sous-titres sont écrits d'après les pages telles
  // qu'elles sont aujourd'hui, pas d'après celles qu'elles remplacent.
  {
    id: "l-pano-0",
    slug: "le-cadre-du-cours",
    titre: "Ce que fait une machine qui apprend",
    resume: "Un agent immobilier annonce un prix sans formule : une machine peut-elle en faire autant ?",
    chapitreId: "ch-ml-1",
    coursId: "c-intro-ml",
    rang: 1,
    genre: "lecture",
    statut: "publie",
    libre: true,
  },
  {
    id: "l-pano-1",
    slug: "programmer-des-regles-ou-apprendre",
    titre: "Programmer des règles, ou apprendre à partir d'exemples",
    resume: "Pourquoi on ne peut pas écrire la règle à la main, et ce que l'humain fournit encore.",
    chapitreId: "ch-ml-1",
    coursId: "c-intro-ml",
    rang: 2,
    genre: "demo",
    statut: "publie",
    libre: true,
  },
  {
    id: "l-pano-2",
    slug: "estimer-le-prix-dun-logement",
    titre: "Le fil conducteur : estimer le prix d'un logement",
    resume: "Estimer le prix d'un logement qu'on n'a jamais vu : le problème qui sert de fil au chapitre.",
    chapitreId: "ch-ml-1",
    coursId: "c-intro-ml",
    rang: 3,
    genre: "lecture",
    statut: "publie",
    libre: true,
  },
  {
    id: "l-pano-3",
    slug: "les-objets-fondamentaux",
    titre: "Les objets fondamentaux",
    resume: "Les quatre objets de tout problème : l'entrée, la réponse attendue, le jeu de données, le modèle.",
    chapitreId: "ch-ml-1",
    coursId: "c-intro-ml",
    rang: 4,
    genre: "lecture",
    statut: "publie",
  },
  {
    id: "l-pano-4",
    slug: "mesurer-lerreur",
    titre: "Mesurer l'erreur : la fonction de perte",
    resume: "Comment on met une note à un modèle, et pourquoi on élève l'écart au carré.",
    chapitreId: "ch-ml-1",
    coursId: "c-intro-ml",
    rang: 5,
    genre: "lecture",
    statut: "publie",
  },
  {
    id: "l-pano-5",
    slug: "apprendre-cest-optimiser",
    titre: "Le paysage des notes, et la table qui triche",
    resume: "Ce que devient la note quand on change un réglage, et pourquoi un sans-faute ne prouve rien.",
    chapitreId: "ch-ml-1",
    coursId: "c-intro-ml",
    rang: 6,
    genre: "demo",
    statut: "publie",
  },
  {
    id: "l-pano-6",
    slug: "les-grandes-familles",
    titre: "Les grandes familles d'apprentissage",
    resume: "Supervisé, non supervisé, renforcement : ce qui les sépare tient dans le fichier qu'on ouvre.",
    chapitreId: "ch-ml-1",
    coursId: "c-intro-ml",
    rang: 7,
    genre: "lecture",
    statut: "publie",
  },
  {
    id: "l-pano-7",
    slug: "regression-ou-classification",
    titre: "Régression ou classification",
    resume: "Prédire une quantité ou choisir une catégorie : reconnaître lequel des deux on a devant soi.",
    chapitreId: "ch-ml-1",
    coursId: "c-intro-ml",
    rang: 8,
    genre: "lecture",
    statut: "publie",
  },
  {
    id: "l-pano-8",
    slug: "demonstration-numerique",
    titre: "Démonstration numérique complète",
    resume: "Le calcul refait à la main sur deux appartements, puis les mêmes lignes écrites en Python.",
    chapitreId: "ch-ml-1",
    coursId: "c-intro-ml",
    rang: 9,
    genre: "demo",
    statut: "publie",
  },
  {
    id: "l-pano-9",
    slug: "un-modele-est-une-fonction-a-boutons",
    titre: "Un modèle est une fonction à boutons",
    resume: "Trois réglages se relisent à la main ; cent mille, non — et ce que cela change.",
    chapitreId: "ch-ml-1",
    coursId: "c-intro-ml",
    rang: 10,
    genre: "lecture",
    statut: "publie",
  },
  {
    id: "l-pano-10",
    slug: "synthese-et-formulaire",
    titre: "Synthèse, formulaire et erreurs fréquentes",
    resume: "Tout le chapitre en une page : le formulaire, le tableau des objets, les erreurs fréquentes.",
    chapitreId: "ch-ml-1",
    coursId: "c-intro-ml",
    rang: 11,
    genre: "lecture",
    statut: "publie",
  },

  // ── Chapitre 2 · Qu'est-ce qu'un réseau de neurones ───────────────────────
  //
  // Douze pages. Le chapitre construit la structure d'un réseau et mesure ce
  // qu'elle vaut ; il ne dit pas comment on l'entraîne. Tous ses nombres
  // sortent de cours/lecon2/mesures.py, exécuté.
  {
    id: "l-res-1",
    slug: "le-cadre-du-reseau",
    titre: "Le cadre du cours",
    resume: "Ce que le chapitre construit : une machine qui lit un chiffre écrit à la main.",
    chapitreId: "ch-ml-2",
    coursId: "c-intro-ml",
    rang: 1,
    genre: "lecture",
    statut: "publie",
  },
  {
    id: "l-res-2",
    slug: "le-probleme-et-le-jeu",
    titre: "Le problème, et le jeu",
    resume: "Les images sur lesquelles on travaille, et à partir de quel score on peut dire qu'une machine a appris.",
    chapitreId: "ch-ml-2",
    coursId: "c-intro-ml",
    rang: 2,
    genre: "demo",
    statut: "publie",
  },
  {
    id: "l-res-3",
    slug: "de-la-grille-au-vecteur",
    titre: "De la grille au vecteur",
    resume: "Mettre une image à plat pour la donner au modèle, et ce qui devient invisible en chemin.",
    chapitreId: "ch-ml-2",
    coursId: "c-intro-ml",
    rang: 3,
    genre: "lecture",
    statut: "publie",
  },
  {
    id: "l-res-4",
    slug: "un-neurone-et-ce-quil-regarde",
    titre: "Un neurone, et ce qu'il regarde",
    resume: "Un neurone est une somme pondérée de pixels, et ses poids se regardent comme une image.",
    chapitreId: "ch-ml-2",
    coursId: "c-intro-ml",
    rang: 4,
    genre: "lecture",
    statut: "publie",
  },
  {
    id: "l-res-5",
    slug: "construire-un-detecteur-de-bord",
    titre: "Construire un détecteur de bord",
    resume: "Fabriquer un détecteur à la main, sans entraînement, et voir où il se laisse tromper.",
    chapitreId: "ch-ml-2",
    coursId: "c-intro-ml",
    rang: 5,
    genre: "demo",
    statut: "publie",
  },
  {
    id: "l-res-6",
    slug: "dix-neurones",
    titre: "Dix neurones",
    resume: "Passer d'un neurone à dix, transformer leurs scores en probabilités, et mesurer ce que ça vaut.",
    chapitreId: "ch-ml-2",
    coursId: "c-intro-ml",
    rang: 6,
    genre: "demo",
    statut: "publie",
  },
  {
    id: "l-res-7",
    slug: "le-plafond-et-dou-il-vient",
    titre: "Le plafond, et d'où il vient",
    resume: "Pourquoi ce premier modèle cesse de progresser, et pourquoi ce n'est pas un problème de réglage.",
    chapitreId: "ch-ml-2",
    coursId: "c-intro-ml",
    rang: 7,
    genre: "demo",
    statut: "publie",
  },
  {
    id: "l-res-8",
    slug: "empiler-ne-suffit-pas",
    titre: "Empiler ne suffit pas",
    resume: "Empiler une couche de plus n'achète rien tant qu'il manque une pièce entre les deux.",
    chapitreId: "ch-ml-2",
    coursId: "c-intro-ml",
    rang: 8,
    genre: "demo",
    statut: "publie",
  },
  {
    id: "l-res-9",
    slug: "casser-la-ligne-droite",
    titre: "Casser la ligne droite",
    resume: "La pièce qui manquait : la fonction d'activation, ReLU et la sigmoïde.",
    chapitreId: "ch-ml-2",
    coursId: "c-intro-ml",
    rang: 9,
    genre: "lecture",
    statut: "publie",
  },
  {
    id: "l-res-10",
    slug: "le-reseau-complet-et-son-compte",
    titre: "Le réseau complet, et son compte",
    resume: "Le réseau écrit une fois pour toutes, et le compte des nombres que personne ne réglera à la main.",
    chapitreId: "ch-ml-2",
    coursId: "c-intro-ml",
    rang: 10,
    genre: "lecture",
    statut: "publie",
  },
  {
    id: "l-res-11",
    slug: "ce-que-la-couche-cachee-a-appris",
    titre: "Ce que la couche cachée a appris",
    resume: "Les neurones cachés détectent-ils des bords, comme on aime le croire ? On va regarder.",
    chapitreId: "ch-ml-2",
    coursId: "c-intro-ml",
    rang: 11,
    genre: "demo",
    statut: "publie",
  },
  {
    id: "l-res-12",
    slug: "synthese-du-reseau",
    titre: "Synthèse, formulaire et erreurs fréquentes",
    resume: "Le chemin d'une image jusqu'au chiffre, le formulaire, et les erreurs fréquentes.",
    chapitreId: "ch-ml-2",
    coursId: "c-intro-ml",
    rang: 12,
    genre: "lecture",
    statut: "publie",
  },

  // ── Chapitre 3 · La descente de gradient ──────────────────────────────────
  //
  // Les douze pages du chapitre. Toutes publiées : le contenu existe, il est
  // vérifié, et chaque nombre qu'il cite sort de cours/lecon3/mesures.py.
  {
    id: "l-desc-1",
    slug: "le-cadre-de-la-descente",
    titre: "Le cadre du cours",
    resume: "Ce que le chapitre règle : d'où viennent les nombres que le chapitre 2 utilisait sans le dire.",
    chapitreId: "ch-ml-3",
    coursId: "c-intro-ml",
    rang: 1,
    genre: "lecture",
    statut: "publie",
    libre: true,
  },
  {
    id: "l-desc-2",
    slug: "ce-quon-a-construit-et-ce-qui-manque",
    titre: "Ce qu'on a construit, et ce qui manque",
    resume: "Le chapitre 2 en une page, et la question qu'il n'a jamais posée : qui choisit les paramètres ?",
    chapitreId: "ch-ml-3",
    coursId: "c-intro-ml",
    rang: 2,
    genre: "lecture",
    statut: "publie",
  },
  {
    id: "l-desc-3",
    slug: "ce-que-veut-dire-apprendre",
    titre: "Ce que veut dire apprendre",
    resume: "On n'écrit pas l'algorithme qui reconnaît un chiffre, on écrit celui qui le règle.",
    chapitreId: "ch-ml-3",
    coursId: "c-intro-ml",
    rang: 3,
    genre: "lecture",
    statut: "publie",
  },
  {
    id: "l-desc-4",
    slug: "au-depart-le-reseau-est-mauvais",
    titre: "Au départ, le réseau est mauvais",
    resume: "Ce que vaut le réseau avant la première mise à jour, mesuré plutôt que supposé.",
    chapitreId: "ch-ml-3",
    coursId: "c-intro-ml",
    rang: 4,
    genre: "demo",
    statut: "publie",
  },
  {
    id: "l-desc-5",
    slug: "dire-au-programme-quil-est-mauvais",
    titre: "Dire au programme qu'il est mauvais",
    resume: "Choisir le nombre qui dit au programme à quel point il se trompe sur un exemple.",
    chapitreId: "ch-ml-3",
    coursId: "c-intro-ml",
    rang: 5,
    genre: "demo",
    statut: "publie",
  },
  {
    id: "l-desc-6",
    slug: "le-cout-sur-tout-le-jeu",
    titre: "Le coût sur tout le jeu",
    resume: "De l'erreur sur un exemple au coût sur tout le jeu : la quantité qu'on cherche à faire baisser.",
    chapitreId: "ch-ml-3",
    coursId: "c-intro-ml",
    rang: 6,
    genre: "lecture",
    statut: "publie",
  },
  {
    id: "l-desc-7",
    slug: "descendre-en-dimension-un",
    titre: "Descendre, en dimension un",
    resume: "Comment faire baisser une courbe quand on ne sait pas où se trouve son minimum.",
    chapitreId: "ch-ml-3",
    coursId: "c-intro-ml",
    rang: 7,
    genre: "lecture",
    statut: "publie",
  },
  {
    id: "l-desc-8",
    slug: "descendre-en-dimension-quelconque",
    titre: "Descendre, en dimension quelconque",
    resume: "Le gradient, le taux d'apprentissage, et l'algorithme de descente écrit en entier.",
    chapitreId: "ch-ml-3",
    coursId: "c-intro-ml",
    rang: 8,
    genre: "demo",
    statut: "publie",
  },
  {
    id: "l-desc-9",
    slug: "pourquoi-on-nutilise-pas-tout-le-jeu",
    titre: "Pourquoi on n'utilise pas tout le jeu",
    resume: "Pourquoi chaque pas se calcule sur un petit paquet d'images plutôt que sur les soixante mille.",
    chapitreId: "ch-ml-3",
    coursId: "c-intro-ml",
    rang: 9,
    genre: "demo",
    statut: "publie",
  },
  {
    id: "l-desc-10",
    slug: "ce-que-le-gradient-encode",
    titre: "Ce que le gradient encode",
    resume: "Ce qu'un gradient contient quand on le regarde, au lieu de simplement l'appliquer.",
    chapitreId: "ch-ml-3",
    coursId: "c-intro-ml",
    rang: 10,
    genre: "lecture",
    statut: "publie",
  },
  {
    id: "l-desc-11",
    slug: "il-ny-a-pas-une-bonne-reponse",
    titre: "Il n'y a pas une bonne réponse",
    resume: "Trois entraînements, trois solutions sans rapport : il n'y a pas un seul bon jeu de réglages.",
    chapitreId: "ch-ml-3",
    coursId: "c-intro-ml",
    rang: 11,
    genre: "demo",
    statut: "publie",
  },
  {
    id: "l-desc-12",
    slug: "la-descente-synthese",
    titre: "Synthèse, formulaire et erreurs fréquentes",
    resume: "L'entraînement en un paragraphe, le formulaire, et les erreurs fréquentes.",
    chapitreId: "ch-ml-3",
    coursId: "c-intro-ml",
    rang: 12,
    genre: "lecture",
    statut: "publie",
  },

  // ── Chapitre 4 · Ce que fait la rétropropagation ──────────────────────────
  //
  // Les douze pages du chapitre. Toutes publiées : le contenu existe, il est
  // vérifié, et chaque nombre qu'il cite sort de cours/lecon4/mesures.py.
  {
    id: "l-retro-1",
    slug: "le-cadre-de-la-retropropagation",
    titre: "Le cadre du cours",
    resume: "Ce que le chapitre règle : comment obtenir le gradient sans le calculer composante par composante.",
    chapitreId: "ch-ml-4",
    coursId: "c-intro-ml",
    rang: 1,
    genre: "lecture",
    statut: "publie",
    libre: true,
  },
  {
    id: "l-retro-2",
    slug: "ce-quon-cherche-et-ce-quon-ne-sait-pas-calculer",
    titre: "Ce qu'on cherche, et ce qu'on ne sait pas encore calculer",
    resume: "Pourquoi la méthode du chapitre précédent est exacte, et pourtant inutilisable pour entraîner.",
    chapitreId: "ch-ml-4",
    coursId: "c-intro-ml",
    rang: 2,
    genre: "lecture",
    statut: "publie",
  },
  {
    id: "l-retro-3",
    slug: "ce-que-la-sortie-reclame",
    titre: "Un seul exemple, et ce que sa sortie réclame",
    resume: "On suit une seule image, et on lit sur des nombres ce que sa sortie réclame.",
    chapitreId: "ch-ml-4",
    coursId: "c-intro-ml",
    rang: 3,
    genre: "demo",
    statut: "publie",
  },
  {
    id: "l-retro-4",
    slug: "la-premiere-voie-le-biais",
    titre: "La première voie : le biais",
    resume: "Corriger un biais : la plus simple des trois corrections, parce que son effet ne passe par rien.",
    chapitreId: "ch-ml-4",
    coursId: "c-intro-ml",
    rang: 4,
    genre: "lecture",
    statut: "publie",
  },
  {
    id: "l-retro-5",
    slug: "la-deuxieme-voie-les-poids",
    titre: "La deuxième voie : les poids",
    resume: "Corriger un poids : la correction est proportionnelle à l'activation qui l'alimente.",
    chapitreId: "ch-ml-4",
    coursId: "c-intro-ml",
    rang: 5,
    genre: "demo",
    statut: "publie",
  },
  {
    id: "l-retro-6",
    slug: "ce-que-hebb-dit-et-ce-quil-ne-dit-pas",
    titre: "Ce que Hebb dit, et ce qu'il ne dit pas",
    resume: "La ressemblance avec la règle de Hebb, ce qu'elle a de juste, et l'endroit où elle casse.",
    chapitreId: "ch-ml-4",
    coursId: "c-intro-ml",
    rang: 6,
    genre: "lecture",
    statut: "publie",
  },
  {
    id: "l-retro-7",
    slug: "la-troisieme-voie-les-activations",
    titre: "La troisième voie : les activations",
    resume: "Une correction qu'on ne peut pas appliquer telle quelle, et d'où vient le mot propagation.",
    chapitreId: "ch-ml-4",
    coursId: "c-intro-ml",
    rang: 7,
    genre: "lecture",
    statut: "publie",
  },
  {
    id: "l-retro-8",
    slug: "dix-demandes-une-somme",
    titre: "Dix demandes, une somme",
    resume: "Dix neurones demandent des choses contraires à la même activation : on additionne, on n'arbitre pas.",
    chapitreId: "ch-ml-4",
    coursId: "c-intro-ml",
    rang: 8,
    genre: "demo",
    statut: "publie",
  },
  {
    id: "l-retro-9",
    slug: "remonter-dune-couche",
    titre: "Remonter d'une couche",
    resume: "Le dernier pas en arrière : la porte ReLU, et les gradients de la première couche.",
    chapitreId: "ch-ml-4",
    coursId: "c-intro-ml",
    rang: 9,
    genre: "demo",
    statut: "publie",
  },
  {
    id: "l-retro-10",
    slug: "un-exemple-ne-suffit-pas",
    titre: "Un exemple ne suffit pas",
    resume: "Ce qui arrive si l'on n'écoute qu'une seule image, et pourquoi on moyenne les corrections.",
    chapitreId: "ch-ml-4",
    coursId: "c-intro-ml",
    rang: 10,
    genre: "demo",
    statut: "publie",
  },
  {
    id: "l-retro-11",
    slug: "lalgorithme-et-sa-verification",
    titre: "L'algorithme, et sa vérification",
    resume: "L'algorithme complet, et la vérification qu'il calcule bien ce qu'il prétend calculer.",
    chapitreId: "ch-ml-4",
    coursId: "c-intro-ml",
    rang: 11,
    genre: "demo",
    statut: "publie",
  },
  {
    id: "l-retro-12",
    slug: "la-retropropagation-synthese",
    titre: "Synthèse, formulaire et erreurs fréquentes",
    resume: "La rétropropagation en un paragraphe, le formulaire, et les erreurs fréquentes.",
    chapitreId: "ch-ml-4",
    coursId: "c-intro-ml",
    rang: 12,
    genre: "lecture",
    statut: "publie",
  },

  // ── Chapitre 5 · Le calcul de la rétropropagation ─────────────────────────
  //
  // Douze pages. Le chapitre établit la forme générale du calcul du gradient :
  // L couches, une activation quelconque, une preuve par récurrence. Il clôt la
  // série sur les réseaux. Tous ses nombres sortent de cours/lecon5/mesures.py,
  // exécuté.
  {
    id: "l-calc-1",
    slug: "le-cadre-du-calcul",
    titre: "Le cadre du cours",
    resume: "Ce que le chapitre établit : le même calcul, pour un réseau d'autant de couches qu'on veut.",
    chapitreId: "ch-ml-5",
    coursId: "c-intro-ml",
    rang: 1,
    genre: "lecture",
    statut: "publie",
  },
  {
    id: "l-calc-2",
    slug: "ce-quil-reste-a-etablir",
    titre: "Ce qu'il reste à établir",
    resume: "Ce que le chapitre 4 a laissé ouvert, et par où on s'y prend pour le fermer.",
    chapitreId: "ch-ml-5",
    coursId: "c-intro-ml",
    rang: 2,
    genre: "lecture",
    statut: "publie",
  },
  {
    id: "l-calc-3",
    slug: "la-regle-de-la-chaine-en-deux-formes",
    titre: "La règle de la chaîne, dans ses deux formes",
    resume: "Les deux formes de la règle de la chaîne, et le critère qui dit laquelle s'applique.",
    chapitreId: "ch-ml-5",
    coursId: "c-intro-ml",
    rang: 3,
    genre: "lecture",
    statut: "publie",
  },
  {
    id: "l-calc-4",
    slug: "larbre-des-dependances",
    titre: "L'arbre des dépendances",
    resume: "De quoi la perte dépend, remonté quantité par quantité jusqu'aux paramètres.",
    chapitreId: "ch-ml-5",
    coursId: "c-intro-ml",
    rang: 4,
    genre: "demo",
    statut: "publie",
  },
  {
    id: "l-calc-5",
    slug: "les-trois-derivees-constitutives",
    titre: "Les trois dérivées constitutives",
    resume: "Les trois dérivées dont tout le reste est fait, chacune tirée de son équation.",
    chapitreId: "ch-ml-5",
    coursId: "c-intro-ml",
    rang: 5,
    genre: "demo",
    statut: "publie",
  },
  {
    id: "l-calc-6",
    slug: "lassemblage-et-le-biais",
    titre: "L'assemblage, et le biais",
    resume: "Les trois dérivées mises bout à bout, et ce qu'un autre coût changerait au produit.",
    chapitreId: "ch-ml-5",
    coursId: "c-intro-ml",
    rang: 6,
    genre: "demo",
    statut: "publie",
  },
  {
    id: "l-calc-7",
    slug: "la-couche-precedente",
    titre: "La couche précédente",
    resume: "Le même calcul une couche plus bas, et la raison pour laquelle il se répète.",
    chapitreId: "ch-ml-5",
    coursId: "c-intro-ml",
    rang: 7,
    genre: "lecture",
    statut: "publie",
  },
  {
    id: "l-calc-8",
    slug: "la-recurrence",
    titre: "La récurrence, et son corollaire",
    resume: "La récurrence qui descend jusqu'à la première couche, et le produit qu'elle fait apparaître.",
    chapitreId: "ch-ml-5",
    coursId: "c-intro-ml",
    rang: 8,
    genre: "demo",
    statut: "publie",
  },
  {
    id: "l-calc-9",
    slug: "plusieurs-neurones-par-couche",
    titre: "Plusieurs neurones par couche",
    resume: "Ce qui change quand chaque couche compte plusieurs neurones, et d'où vient la transposée.",
    chapitreId: "ch-ml-5",
    coursId: "c-intro-ml",
    rang: 9,
    genre: "lecture",
    statut: "publie",
  },
  {
    id: "l-calc-10",
    slug: "la-forme-vectorielle",
    titre: "La forme vectorielle",
    resume: "Les mêmes équations écrites sans indices, en quatre lignes.",
    chapitreId: "ch-ml-5",
    coursId: "c-intro-ml",
    rang: 10,
    genre: "demo",
    statut: "publie",
  },
  {
    id: "l-calc-11",
    slug: "ce-que-la-profondeur-coute",
    titre: "Ce que la profondeur coûte, ce que l'algorithme économise",
    resume: "Ce que la profondeur fait au signal d'erreur, et ce que l'algorithme coûte.",
    chapitreId: "ch-ml-5",
    coursId: "c-intro-ml",
    rang: 11,
    genre: "demo",
    statut: "publie",
  },
  {
    id: "l-calc-12",
    slug: "synthese-de-la-serie",
    titre: "Synthèse de la série, formulaire et ressources",
    resume: "Les cinq chapitres bout à bout, le formulaire, et les erreurs fréquentes.",
    chapitreId: "ch-ml-5",
    coursId: "c-intro-ml",
    rang: 12,
    genre: "lecture",
    statut: "publie",
  },

  // ── Chapitre 2 · l'ancien arc, RETIRÉ DU SOMMAIRE le 31 août 2026 ────────
  //
  // Les dix leçons `l-sup-0` à `l-sup-9` décrivaient l'arc précédent, où le
  // chapitre 2 était « L'apprentissage supervisé, en profondeur ». Cet arc est
  // remplacé par les chapitres 2 à 5 : réseau, descente, rétropropagation,
  // calcul. Elles ne sont plus servies. Aucun contenu ne leur avait été versé :
  // elles n'ont jamais eu de fichier ailleurs que dans ce tableau, et c'est
  // pourquoi elles y restent, inertes — elles sont la seule trace du plan
  // qu'elles décrivaient, et on peut vouloir y revenir.
  //
  // // ── Chapitre 2 · L'apprentissage supervisé, en profondeur ─────────────────
  // //
  // // Le plan est arrêté : il vient de la spécification du chapitre 2, qui fixe
  // // ses cinq parties, ses chiffres et ses marqueurs. Le contenu, lui, n'est pas
  // // encore versé ici. Les dix leçons sont donc ANNONCÉES, sans durée : une
  // // durée est une promesse, et on ne promet pas ce qu'on n'a pas écrit.
  // //
  // // L'appareil expérimental, lui, existe déjà et tourne : cours/lecon2/
  // // regression.py, classification.py, retropropagation.py, entrainement.py.
  // {
  //   id: "l-sup-0",
  //   slug: "le-cadre-du-supervise",
  //   titre: "Le cadre du cours",
  //   resume: "Deux actes annoncés, neuf objectifs, et six dettes contractées.",
  //   chapitreId: "ch-ml-2",
  //   coursId: "c-intro-ml",
  //   rang: 1,
  //   genre: "lecture",
  //   minutes: 0,
  //   statut: "annonce",
  // },
  // {
  //   id: "l-sup-1",
  //   slug: "le-cadre-supervise-formalise",
  //   titre: "Le cadre supervisé, formalisé",
  //   resume: "Espace d'hypothèses, risque empirique, et la distinction entraînement/inférence.",
  //   chapitreId: "ch-ml-2",
  //   coursId: "c-intro-ml",
  //   rang: 2,
  //   genre: "lecture",
  //   minutes: 0,
  //   statut: "annonce",
  // },
  // {
  //   id: "l-sup-2",
  //   slug: "la-regression-lineaire",
  //   titre: "La régression linéaire, de bout en bout",
  //   resume: "La première vraie dérivation de gradient du parcours, puis 1000 pas exécutés.",
  //   chapitreId: "ch-ml-2",
  //   coursId: "c-intro-ml",
  //   rang: 3,
  //   genre: "demo",
  //   minutes: 0,
  //   statut: "annonce",
  // },
  // {
  //   id: "l-sup-3",
  //   slug: "ce-quon-veut-vraiment-minimiser",
  //   titre: "Ce qu'on veut vraiment minimiser, et pourquoi on ne peut pas",
  //   resume: "La perte 0-1 n'a pas de gradient, et la quadratique punit les points bien classés.",
  //   chapitreId: "ch-ml-2",
  //   coursId: "c-intro-ml",
  //   rang: 4,
  //   genre: "demo",
  //   minutes: 0,
  //   statut: "annonce",
  // },
  // {
  //   id: "l-sup-4",
  //   slug: "la-sigmoide-et-lentropie-croisee",
  //   titre: "La sigmoïde et l'entropie croisée, dérivées",
  //   resume: "L'inverse du log-cote, le maximum de vraisemblance, et un facteur 28 mesuré.",
  //   chapitreId: "ch-ml-2",
  //   coursId: "c-intro-ml",
  //   rang: 5,
  //   genre: "demo",
  //   minutes: 0,
  //   statut: "annonce",
  // },
  // {
  //   id: "l-sup-5",
  //   slug: "le-multi-classe-et-le-softmax",
  //   titre: "Le multi-classe, et le softmax",
  //   resume: "Trois mises en échec du codage numérique, puis le softmax dérivé comme la sigmoïde.",
  //   chapitreId: "ch-ml-2",
  //   coursId: "c-intro-ml",
  //   rang: 6,
  //   genre: "lecture",
  //   minutes: 0,
  //   statut: "annonce",
  // },
  // {
  //   id: "l-sup-6",
  //   slug: "pourquoi-le-lineaire-ne-suffit-pas",
  //   titre: "Pourquoi le linéaire ne suffit pas",
  //   resume: "L'image devient un vecteur, et une preuve par XOR ferme la porte au modèle linéaire.",
  //   chapitreId: "ch-ml-2",
  //   coursId: "c-intro-ml",
  //   rang: 7,
  //   genre: "lecture",
  //   minutes: 0,
  //   statut: "annonce",
  // },
  // {
  //   id: "l-sup-7",
  //   slug: "la-retropropagation",
  //   titre: "La rétropropagation",
  //   resume: "La règle de la chaîne, organisée, puis exécutée entièrement à la main sur 2 vers 2 vers 2.",
  //   chapitreId: "ch-ml-2",
  //   coursId: "c-intro-ml",
  //   rang: 8,
  //   genre: "demo",
  //   minutes: 0,
  //   statut: "annonce",
  // },
  // {
  //   id: "l-sup-8",
  //   slug: "lentrainement-complet",
  //   titre: "L'entraînement complet, en code",
  //   resume: "101 770 paramètres, 28 140 mises à jour, et 0,9814 sur des chiffres jamais vus.",
  //   chapitreId: "ch-ml-2",
  //   coursId: "c-intro-ml",
  //   rang: 9,
  //   genre: "demo",
  //   minutes: 0,
  //   statut: "annonce",
  // },
  // {
  //   id: "l-sup-9",
  //   slug: "synthese-du-supervise",
  //   titre: "Synthèse, formulaire et erreurs fréquentes",
  //   resume: "Le trajet complet en un paragraphe, puis ce qu'il faut garder sous la main.",
  //   chapitreId: "ch-ml-2",
  //   coursId: "c-intro-ml",
  //   rang: 10,
  //   genre: "lecture",
  //   minutes: 0,
  //   statut: "annonce",
  // },
  //
  //

  // ── L'optimisation de l'entraînement · le cours `c-optim` ─────────────────
  //
  // Décalé du rang 3 au rang 6 le 31 août 2026 : les chapitres 3, 4 et 5
  // construisent désormais ce que ces huit leçons supposaient acquis. Leur
  // contenu n'a pas été relu à cette occasion — il peut redire ce que les
  // nouveaux chapitres établissent.
  //
  // SORTI DU COURS D'INTRODUCTION le 13 septembre 2026 : il demande
  // Cauchy-Schwarz, un développement limité et une diagonalisation, ce qu'un
  // cours d'entrée marqué « Débutant » ne peut pas réclamer. Il devient un
  // cours du parcours de maths. Ces huit pages n'ont pas bougé d'un mot, et
  // leurs slugs non plus ; ce qui change est le cours qui les porte, donc le
  // premier segment de leur adresse.
  {
    id: "l-optim-0",
    slug: "le-cadre-de-loptimisation",
    titre: "Le cadre de cette leçon",
    resume: "Quatre réglages de l'entraînement restés sans justification, et ce que ce cours en fait.",
    chapitreId: "ch-ml-6",
    coursId: "c-optim",
    rang: 1,
    genre: "lecture",
    statut: "publie",
  },
  {
    id: "l-optim-1",
    slug: "pourquoi-cette-direction",
    titre: "Pourquoi cette direction, et pourquoi ce signe",
    resume: "Pourquoi on descend dans la direction opposée au gradient, et pas dans une autre.",
    chapitreId: "ch-ml-6",
    coursId: "c-optim",
    rang: 2,
    genre: "demo",
    statut: "publie",
  },
  {
    id: "l-optim-2",
    slug: "le-lot-complet-et-le-mini-lot",
    titre: "Le lot complet, et le mini-lot",
    resume: "Ce que coûte un pas calculé sur tout le jeu, et ce que le mini-lot y change.",
    chapitreId: "ch-ml-6",
    coursId: "c-optim",
    rang: 3,
    genre: "demo",
    statut: "publie",
  },
  {
    id: "l-optim-3",
    slug: "le-pas-dapprentissage",
    titre: "Le pas d'apprentissage",
    resume: "Jusqu'où on peut allonger le pas avant que la descente cesse de descendre.",
    chapitreId: "ch-ml-6",
    coursId: "c-optim",
    rang: 4,
    genre: "demo",
    statut: "publie",
  },
  {
    id: "l-optim-4",
    slug: "linitialisation",
    titre: "L'initialisation",
    resume: "Pourquoi on ne part pas de zéro, et d'où vient l'échelle du tirage au hasard.",
    chapitreId: "ch-ml-6",
    coursId: "c-optim",
    rang: 5,
    genre: "lecture",
    statut: "publie",
  },
  {
    id: "l-optim-5",
    slug: "la-standardisation-des-entrees",
    titre: "La standardisation des entrées",
    resume: "Pourquoi remettre les entrées à la même échelle accélère l'entraînement.",
    chapitreId: "ch-ml-6",
    coursId: "c-optim",
    rang: 6,
    genre: "lecture",
    statut: "publie",
  },
  {
    id: "l-optim-6",
    slug: "les-gradients-evanescents",
    titre: "Les gradients évanescents",
    resume: "Ce qui arrive au gradient quand il traverse plusieurs couches de sigmoïdes.",
    chapitreId: "ch-ml-6",
    coursId: "c-optim",
    rang: 7,
    genre: "lecture",
    statut: "publie",
  },
  {
    id: "l-optim-7",
    slug: "loptimisation-synthese",
    titre: "Synthèse de l'optimisation, et formulaire",
    resume: "L'optimisation en un paragraphe, le formulaire, et les erreurs fréquentes.",
    chapitreId: "ch-ml-6",
    coursId: "c-optim",
    rang: 8,
    genre: "lecture",
    statut: "publie",
  },
];
